/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_5_biblioteca;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mauri
 */
public class Principal extends javax.swing.JFrame {

    public static ArrayList<Libro> listaLibros = new ArrayList<>();
    public static ArrayList<Estudiante> listaEstudiantes = new ArrayList<>();
    public static ArrayList<Prestamo> listaPrestamos = new ArrayList<>();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RegitrarLibros = new javax.swing.JButton();
        GuardarDatos = new javax.swing.JButton();
        RegistrarEstudiantes = new javax.swing.JButton();
        CargarDatos = new javax.swing.JButton();
        ListarLibros = new javax.swing.JButton();
        ListarEstudiantes = new javax.swing.JButton();
        PrestarLibro = new javax.swing.JButton();
        ListarPrestamos = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Biblioteca");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        RegitrarLibros.setBackground(new java.awt.Color(153, 153, 255));
        RegitrarLibros.setText("Registrar Libros");
        RegitrarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegitrarLibrosActionPerformed(evt);
            }
        });

        GuardarDatos.setBackground(new java.awt.Color(153, 153, 255));
        GuardarDatos.setText("Guardar Datos");
        GuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDatosActionPerformed(evt);
            }
        });

        RegistrarEstudiantes.setBackground(new java.awt.Color(153, 153, 255));
        RegistrarEstudiantes.setText("Registrar Estudiantes");
        RegistrarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEstudiantesActionPerformed(evt);
            }
        });

        CargarDatos.setBackground(new java.awt.Color(153, 153, 255));
        CargarDatos.setText("Cargar Datos");
        CargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarDatosActionPerformed(evt);
            }
        });

        ListarLibros.setBackground(new java.awt.Color(153, 153, 255));
        ListarLibros.setText("Listar Libros");
        ListarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarLibrosActionPerformed(evt);
            }
        });

        ListarEstudiantes.setBackground(new java.awt.Color(153, 153, 255));
        ListarEstudiantes.setText("Listar Estudiantes");
        ListarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarEstudiantesActionPerformed(evt);
            }
        });

        PrestarLibro.setBackground(new java.awt.Color(153, 153, 255));
        PrestarLibro.setText("Prestar Libro");
        PrestarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrestarLibroActionPerformed(evt);
            }
        });

        ListarPrestamos.setBackground(new java.awt.Color(153, 153, 255));
        ListarPrestamos.setText("Listar Prestamos");
        ListarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPrestamosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RegitrarLibros)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ListarEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ListarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(RegistrarEstudiantes)
                                        .addGap(41, 41, 41)
                                        .addComponent(PrestarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(GuardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(CargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegitrarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrarEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrestarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListarEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegitrarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegitrarLibrosActionPerformed
        new JFrameLibro().setVisible(true);
    }//GEN-LAST:event_RegitrarLibrosActionPerformed

    private void GuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDatosActionPerformed
        Persistencia.guardarLibros(listaLibros);
        Persistencia.guardarEstudiantes(listaEstudiantes);
        Persistencia.guardarPrestamos(listaPrestamos);
        JOptionPane.showMessageDialog(this, "Datos guardados");
    }//GEN-LAST:event_GuardarDatosActionPerformed

    private void CargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarDatosActionPerformed
        
        listaLibros = Persistencia.cargarLibros();
        listaEstudiantes = Persistencia.cargarEstudiantes();
        listaPrestamos = Persistencia.cargarPrestamos();
        JOptionPane.showMessageDialog(this, "Datos cargados");
        
    }//GEN-LAST:event_CargarDatosActionPerformed

    private void RegistrarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEstudiantesActionPerformed
        new JFrameEstudiante().setVisible(true);
    }//GEN-LAST:event_RegistrarEstudiantesActionPerformed

    private void ListarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarLibrosActionPerformed
        StringBuilder sb = new StringBuilder();
        for (Libro l : listaLibros) sb.append(l).append("\n");
        JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_ListarLibrosActionPerformed

    private void ListarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarEstudiantesActionPerformed
       StringBuilder sb = new StringBuilder();
        for (Estudiante e : listaEstudiantes) sb.append(e).append("\n");
        JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_ListarEstudiantesActionPerformed

    private void PrestarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrestarLibroActionPerformed
        new JFramePrestamo().setVisible(true);
    }//GEN-LAST:event_PrestarLibroActionPerformed

    private void ListarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPrestamosActionPerformed
        StringBuilder sb = new StringBuilder();
        for (Prestamo p : listaPrestamos) sb.append(p).append("\n");
        JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_ListarPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarDatos;
    private javax.swing.JButton GuardarDatos;
    private javax.swing.JButton ListarEstudiantes;
    private javax.swing.JButton ListarLibros;
    private javax.swing.JButton ListarPrestamos;
    private javax.swing.JButton PrestarLibro;
    private javax.swing.JButton RegistrarEstudiantes;
    private javax.swing.JButton RegitrarLibros;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
